package me.white.itemeditor.command;

import com.mojang.brigadier.CommandDispatcher;
import com.mojang.brigadier.tree.LiteralCommandNode;

import me.white.itemeditor.node.*;
import net.fabricmc.fabric.api.client.command.v2.ClientCommandManager;
import net.fabricmc.fabric.api.client.command.v2.FabricClientCommandSource;
import net.minecraft.command.CommandRegistryAccess;

public class EditCommand {
	public static void register(CommandDispatcher<FabricClientCommandSource> dispatcher, CommandRegistryAccess registryAccess) {
		LiteralCommandNode<FabricClientCommandSource> editNode = ClientCommandManager
			.literal("edit")
			.build();
		
		LiteralCommandNode<FabricClientCommandSource> namespacedEditNode = ClientCommandManager
			.literal("itemeditor:edit")
			.redirect(editNode)
			.build();

		// ... material ...
		MaterialNode.register(editNode, registryAccess);
		// ... name ...
		NameNode.register(editNode);
		// ... lore ...
		LoreNode.register(editNode);
		// ... count ...
		CountNode.register(editNode);
		// ... model ...
		ModelNode.register(editNode);
		// ... enchantment ...
		EnchantmentNode.register(editNode, registryAccess);
		// ... get ...
		GetNode.register(editNode, registryAccess);
		// ... attribute ...
		AttributeNode.register(editNode, registryAccess);
		// ... color ...
		ColorNode.register(editNode);
		// ... hideflags ...
		FlagsNode.register(editNode);
		// ... equip
		EquipNode.register(editNode);
		// ... unbreakable
		UnbreakableNode.register(editNode);
		// ... whitelist ...
		WhitelistNode.register(editNode, registryAccess);
		// ... durability ...
		DurabilityNode.register(editNode);
		// ... data ...
		DataNode.register(editNode);
		// ... book ...
		BookNode.register(editNode);
		// ... head ...
		HeadNode.register(editNode, registryAccess);
		// ... trim ...
		TrimNode.register(editNode, registryAccess);
		// ... firework ...
		FireworkNode.register(editNode);
		// ... banner ...
		BannerNode.register(editNode, registryAccess);
		// ... potion ...
		PotionNode.register(editNode, registryAccess);

		// BETA RELEASE

		// ... script ...
		// ... items ...
		// ... entity ...
		// ... optimize ...
		
		dispatcher.getRoot().addChild(editNode);
		dispatcher.getRoot().addChild(namespacedEditNode);
	}
}
